#!/bin/bash
PREFIX=/home/tiago/win32
export PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"
export PKG_CONFIG_LIBDIR="$PREFIX/lib/pkgconfig"
export CFLAGS=
export LDFLAGS=
M=i586-mingw32msvc
cd src
scintilla_dir="$1"
shift
[ -d "$scintilla_dir" ] || exit 1
make -f mingw32-cross.mak BASEDIR="$PREFIX" SCINTILLADIR="$scintilla_dir" COMPLIB="../bin/libscintilla.a" "$@"
